name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.MD'
      - '**.gitkeep'
      - '**.gitignore'
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: compile with debugging functionality
      printf:
        type: choice
        description: wich debugging messages variant to use
        options:
        - NONE
        - PRINTF
        - EE_SIO
        - SCR
        - UDPTTY

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:

      - name: Install dependencies
        run: |
          apk add build-base git p7zip

      - uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow

      - name: compilation opts
        if: github.event.inputs.debug == true
        run: |
          echo "DEBUG=$(echo DEBUG=1)" >> $GITHUB_ENV

      - name: Compile PS2 build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2/ ${{ env.DEBUG }} PRINTF=${{ github.event.inputs.printf }}

      - name: Compile PS2 MX4SIO build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2_MX4SIO/ MX4SIO=1 ${{ env.DEBUG }} PRINTF=${{ github.event.inputs.printf }}

      - name: Compile PSX build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PSX/ PSX=1 ${{ env.DEBUG }} PRINTF=${{ github.event.inputs.printf }}

      - name: Compile PS2 HDD build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2_HDD/ HDD=1 ${{ env.DEBUG }} PRINTF=${{ github.event.inputs.printf }}

      - name: Compile PS2 MMCE build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PS2_MMCE/ MMCE=1 ${{ env.DEBUG }} PRINTF=${{ github.event.inputs.printf }}

      - name: Compile PSX MMCE build
        run: |
          make release COMMIT_HASH=${GITHUB_SHA::7} BINDIR=PSX_MMCE/ PSX=1 MMCE=1 ${{ env.DEBUG }} PRINTF=${{ github.event.inputs.printf }}

      - name: prepare release folder
        run: |
          cp LICENSE release/LICENSE.TXT
          cp README.md release/README.md
          mv PS2/ release/PS2/
          mv PSX/ release/PSX/
          mv PS2_HDD/ release/PS2_HDD/
          mv PS2_MX4SIO/ release/PS2_MX4SIO/
          mv PS2_MMCE/ release/PS2_MMCE/
          mv PSX_MMCE/ release/PSX_MMCE/

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PS2BBL
          path: |
            release/*
